// frontend/src/components/admin/CategoryAdmin.vue
<template>
	<div class="category-admin">
		<b-form>
			<input type="hidden" id="category-id" v-model="category.id" />
			<b-form-group label="Nome:" label-for="category-name">
				<b-form-input
					id="category-name"
					type="text"
					v-model="category.name"
					required
					:readonly="mode === 'remove'"
					placeholder="Informe o Nome da Categoria..."
				></b-form-input>
			</b-form-group>
			<b-form-group label="Categoria Pai:" label-for="category-parent-id">
				<b-form-select
					v-if="mode === 'save'"
					id="category-parent-id"
					:options="categories"
					v-model="category.parentId"
				></b-form-select>
				<b-form-input
					v-else
					id="category-parent-id"
					type="text"
					v-model="category.path"
					readonly
				></b-form-input>
			</b-form-group>
			<b-button variant="primary" v-if="mode === 'save'" @click="save"
				>Salvar</b-button
			>
			<b-button variant="danger" v-if="mode === 'remove'" @click="remove"
				>Excluir</b-button
			>
			<b-button class="ml-2" @click="reset">Cancelar</b-button>
		</b-form>
		<hr />
		<b-table hover striped :items="categories" :fields="fields">
			<template slot="actions" slot-scope="data">
				<b-button
					variant="warning"
					@click="loadCategory(data.item)"
					class="mr-2"
				>
					<i class="fa fa-pencil"></i>
				</b-button>
				<b-button variant="danger" @click="loadCategory(data.item, 'remove')">
					<i class="fa fa-trash"></i>
				</b-button>
			</template>
		</b-table>
	</div>
</template>

<script>
	import { baseApiUrl, showError } from "@/global";
	import axios from "axios";

	export default {
		name: "CategoryAdmin",
		data: function () {
			return {
				mode: "save",
				category: {},
				categories: [],
				fields: [
					{ key: "id", label: "Código", sortable: true },
					{ key: "name", label: "Nome", sortable: true },
					{ key: "path", label: "Caminho", sortable: true },
					{ key: "actions", label: "Ações" },
				],
			};
		},
		methods: {
			loadCategories() {
				const url = `${baseApiUrl}/categories`;
				axios.get(url).then((res) => {
					this.categories = res.data.map((category) => {
						return { ...category, value: category.id, text: category.path };
					});
				});
			},
			reset() {
				this.mode = "save";
				this.category = {};
				this.loadCategories();
			},
			save() {
				const method = this.category.id ? "put" : "post";
				const id = this.category.id ? `/${this.category.id}` : "";
				axios[method](`${baseApiUrl}/categories${id}`, this.category)
					.then(() => {
						this.$toasted.global.defaultSuccess();
						this.reset();
					})
					.catch(showError);
			},
			remove() {
				const id = this.category.id;
				axios
					.delete(`${baseApiUrl}/categories/${id}`)
					.then(() => {
						this.$toasted.global.defaultSuccess();
						this.reset();
					})
					.catch(showError);
			},
			loadCategory(category, mode = "save") {
				this.mode = mode;
				this.category = { ...category };
			},
		},
		mounted() {
			this.loadCategories();
		},
	};
</script>

<style>
</style>

// frontend-react/src/components/admin/CategoryAdmin.jsx
import React, { useState, useMemo } from 'react'
import axios from 'axios'
import { baseApiUrl, showError, showSuccess } from '../../global'
import FormGroupControl from '../utils/FormGroupControl'
import DataSelect from '../utils/DataSelect'
import Form from 'react-bootstrap/Form'
import Button from 'react-bootstrap/Button'
import useObjectState from '../../hooks/useObjectState'
import useLoadData from '../../hooks/useLoadData'
import DataTable from '../utils/DataTable'

export default function CategoryAdmin() {
  const [mode, setMode] = useState('save')
  const [validated, setValidated] = useState(false)
  const initialCategory = {
    id: undefined,
    name: '',
    parentId: null,
  }
  const [category, setCategory] = useObjectState(initialCategory)
  const [categories, loadCategories] = useLoadData('/categories')
  const fields = useMemo(() => {
    const loadCategory = (category, mode = 'save') => {
      setMode(mode)
      setCategory({ ...category })
    }
    return [
      { key: 'id', label: 'Código', sortable: true },
      { key: 'name', label: 'Nome', sortable: true },
      { key: 'path', label: 'Caminho', sortable: true },
      {
        key: 'actions',
        label: 'Ações',
        formatter: (item) => {
          return (
            <div className="d-flex gap-2 flex-wrap">
              <Button variant="warning" onClick={() => loadCategory(item)}>
                <i className="fa fa-pencil"></i>
              </Button>
              <Button
                variant="danger"
                onClick={() => loadCategory(item, 'remove')}>
                <i className="fa fa-trash"></i>
              </Button>
            </div>
          )
        },
      },
    ]
    // eslint-disable-next-line
  }, [])

  const reset = () => {
    setMode('save')
    setCategory(initialCategory)
    setValidated(false)
  }

  const submit = () => {
    setValidated(true)
    const method = mode === 'remove' ? 'delete' : category.id ? 'put' : 'post'
    const id = category.id ? `/${category.id}` : ''
    axios[method](`${baseApiUrl}/categories${id}`, category)
      .then(() => {
        showSuccess()
        reset()
        loadCategories()
      })
      .catch(showError)
  }

  return (
    <div>
      <Form
        className="d-grid gap-3"
        onReset={(e) => {
          e.preventDefault()
          reset()
        }}
        noValidate
        validated={validated}
        onSubmit={(e) => {
          e.preventDefault()
          submit()
        }}>
        <input type="hidden" id="category-id" value={category.id || ''} />
        <FormGroupControl
          type="name"
          value={category.name}
          label="Nome:"
          controlId={'category-name'}
          placeholder="Digite o Nome da Categoria"
          required
          readOnly={mode === 'remove'}
          onChange={(e) => setCategory({ name: e.target.value })}
        />
        <Form.Group controlId="category-parent-id">
          <Form.Label>
            {mode === 'save' ? 'Categoria Pai:' : 'Caminho:'}
          </Form.Label>
          {mode === 'save' ? (
            <DataSelect
              value={category.parentId}
              items={categories.map((category) => {
                return { ...category, text: category.path, value: category.id }
              })}
              onChange={(e) =>
                setCategory({ parentId: e.target.value || null })
              }
            />
          ) : (
            <Form.Control type="text" value={category.path} readOnly />
          )}
        </Form.Group>
        <div className="d-flex gap-2">
          {mode === 'save' ? (
            <Button variant="primary" type="submit">
              Salvar
            </Button>
          ) : (
            <Button variant="danger" type="submit">
              Excluir
            </Button>
          )}
          <Button variant="secondary" type="reset">
            Cancelar
          </Button>
        </div>
      </Form>
      <hr />
      <DataTable hover striped responsive items={categories} fields={fields} />
    </div>
  )
}
