// frontend/src/components/admin/UserAdmin.vue
<template>
	<div class="user-admin">
		<b-form>
			<input type="hidden" id="user-id" v-model="user.id" />
			<b-row>
				<b-col md="6" sm="12">
					<b-form-group label="Nome:" label-for="user-name">
						<b-form-input
							id="user-name"
							type="text"
							v-model="user.name"
							required
							:readonly="mode === 'remove'"
							placeholder="Informe o Nome do Usuário..."
						></b-form-input>
					</b-form-group>
				</b-col>
				<b-col md="6" sm="12">
					<b-form-group label="E-mail:" label-for="user-email">
						<b-form-input
							id="user-email"
							type="text"
							v-model="user.email"
							required
							:readonly="mode === 'remove'"
							placeholder="Informe o E-mail do Usuário..."
						></b-form-input>
					</b-form-group>
				</b-col>
			</b-row>
			<b-form-checkbox
				id="user-admin"
				v-show="mode === 'save'"
				v-model="user.admin"
				class="mt-3 mb-3"
			>
				Administrador?
			</b-form-checkbox>
			<b-row v-show="mode === 'save'">
				<b-col md="6" sm="12">
					<b-form-group label="Senha:" label-for="user-password">
						<b-form-input
							id="user-password"
							type="password"
							v-model="user.password"
							required
							placeholder="Informe a Senha do Usuário..."
						></b-form-input>
					</b-form-group>
				</b-col>
				<b-col md="6" sm="12">
					<b-form-group
						label="Confirmação de Senha:"
						label-for="user-confirm-password"
					>
						<b-form-input
							id="user-confirm-password"
							type="password"
							v-model="user.confirmPassword"
							required
							placeholder="Confirme a Senha do Usuário..."
						></b-form-input>
					</b-form-group>
				</b-col>
			</b-row>
			<b-row>
				<b-col xs="12">
					<b-button variant="primary" v-if="mode === 'save'" @click="save"
						>Salvar</b-button
					>
					<b-button variant="danger" v-if="mode === 'remove'" @click="remove"
						>Excluir</b-button
					>
					<b-button class="ml-2" @click="reset">Cancelar</b-button>
				</b-col>
			</b-row>
		</b-form>
		<hr />
		<b-table hover striped :items="users" :fields="fields">
			<template slot="actions" slot-scope="data">
				<b-button variant="warning" @click="loadUser(data.item)" class="mr-2">
					<i class="fa fa-pencil"></i>
				</b-button>
				<b-button variant="danger" @click="loadUser(data.item, 'remove')">
					<i class="fa fa-trash"></i>
				</b-button>
			</template>
		</b-table>
	</div>
</template>

<script>
	import { baseApiUrl, showError } from "@/global";
	import axios from "axios";

	export default {
		name: "UserAdmin",
		data: function () {
			return {
				mode: "save",
				user: {},
				users: [],
				fields: [
					{ key: "id", label: "Código", sortable: true },
					{ key: "name", label: "Nome", sortable: true },
					{ key: "email", label: "E-mail", sortable: true },
					{
						key: "admin",
						label: "Administrador",
						sortable: true,
						formatter: (value) => (value ? "Sim" : "Não"),
					},
					{ key: "actions", label: "Ações" },
				],
			};
		},
		methods: {
			loadUsers() {
				const url = `${baseApiUrl}/users`;
				axios.get(url).then((res) => {
					this.users = res.data;
				});
			},
			reset() {
				this.mode = "save";
				this.user = {};
				this.loadUsers();
			},
			save() {
				const method = this.user.id ? "put" : "post";
				const id = this.user.id ? `/${this.user.id}` : "";
				axios[method](`${baseApiUrl}/users${id}`, this.user)
					.then(() => {
						this.$toasted.global.defaultSuccess();
						this.reset();
					})
					.catch(showError);
			},
			remove() {
				const id = this.user.id;
				axios
					.delete(`${baseApiUrl}/users/${id}`)
					.then(() => {
						this.$toasted.global.defaultSuccess();
						this.reset();
					})
					.catch(showError);
			},
			loadUser(user, mode = "save") {
				this.mode = mode;
				this.user = { ...user };
			},
		},
		mounted() {
			this.loadUsers();
		},
	};
</script>

<style>
</style>

// frontend-react/src/components/admin/UserAdmin.jsx
import React, { useState, useMemo } from 'react'
import useObjectState from '../../hooks/useObjectState'
import useLoadData from '../../hooks/useLoadData'
import axios from 'axios'
import { baseApiUrl, showError, showSuccess } from '../../global'
import Table from '../utils/DataTable'
import Form from 'react-bootstrap/Form'
import Button from 'react-bootstrap/Button'
import Col from 'react-bootstrap/Col'
import Row from 'react-bootstrap/Row'
import FormGroup from '../utils/FormGroupControl'

export default function UserAdmin() {
  const [users, loadUsers] = useLoadData('/users')
  const [validated, setValidated] = useState(false)
  const [mode, setMode] = useState('save')
  const initialUser = {
    id: undefined,
    admin: false,
    name: '',
    email: '',
    password: '',
    confirmPassword: '',
  }
  const [user, setUser] = useObjectState(initialUser)

  const fields = useMemo(() => {
    const loadUser = (user, mode = 'save') => {
      setMode(mode)
      setUser({ ...user })
    }
    return [
      { key: 'id', label: 'Código', sortable: true },
      { key: 'name', label: 'Nome', sortable: true },
      { key: 'email', label: 'E-mail', sortable: true },
      {
        key: 'admin',
        label: 'Administrador',
        sortable: true,
        formatter: (item) => (item['admin'] ? 'Sim' : 'Não'),
      },
      {
        key: 'actions',
        label: 'Ações',
        formatter: (item) => (
          <div className="d-flex gap-2 flex-wrap">
            <Button variant="warning" onClick={() => loadUser(item)}>
              <i className="fa fa-pencil"></i>
            </Button>
            <Button variant="danger" onClick={() => loadUser(item, 'remove')}>
              <i className="fa fa-trash"></i>
            </Button>
          </div>
        ),
      },
    ]
    // eslint-disable-next-line
  }, [])

  const reset = () => {
    setMode('save')
    setUser(initialUser)
    setValidated(false)
  }

  const submit = () => {
    setValidated(true)
    const method = mode === 'remove' ? 'delete' : user.id ? 'put' : 'post'
    const id = user.id ? `/${user.id}` : ''
    axios[method](`${baseApiUrl}/users${id}`, user)
      .then(() => {
        showSuccess()
        reset()
        loadUsers()
      })
      .catch(showError)
  }

  return (
    <div>
      <Form
        noValidate
        onSubmit={(e) => {
          e.preventDefault()
          submit()
        }}
        onReset={(e) => {
          e.preventDefault()
          reset()
        }}
        validated={validated}
        className="d-grid gap-3">
        <input type="hidden" id="user-id" value={user.id || ''} />
        <Row>
          <FormGroup
            as={Col}
            md={6}
            sm={12}
            controlId="user-name"
            required
            type="text"
            label="Nome:"
            placeholder="Informe o Nome do Usuário..."
            value={user.name}
            readOnly={mode === 'remove'}
            onChange={(e) => setUser({ name: e.target.value })}
          />
          <FormGroup
            as={Col}
            md={6}
            sm={12}
            controlId="user-email"
            required
            type="email"
            label="E-mail:"
            placeholder="Informe o E-mail do Usuário..."
            value={user.email}
            readOnly={mode === 'remove'}
            onChange={(e) => setUser({ email: e.target.value })}
          />
        </Row>
        {mode === 'save' && (
          <>
            <Form.Check
              id="user-admin"
              type="checkbox"
              label="Administrador?"
              checked={user.admin}
              onChange={(e) => setUser({ admin: e.currentTarget.checked })}
            />
            <Row>
              <FormGroup
                as={Col}
                md={6}
                sm={12}
                controlId="user-password"
                required
                type="password"
                label="Senha:"
                placeholder="Informe a Senha do Usuário..."
                value={user.password}
                onChange={(e) => setUser({ password: e.target.value })}
              />
              <FormGroup
                as={Col}
                md={6}
                sm={12}
                controlId="user-password-confirmation"
                required
                type="password"
                label="Confirmação de Senha:"
                placeholder="Confirme a Senha..."
                value={user.confirmPassword}
                onChange={(e) => setUser({ confirmPassword: e.target.value })}
              />
            </Row>
          </>
        )}
        <Row>
          <Col xs={12} className="d-flex gap-2">
            {mode === 'save' ? (
              <Button variant="primary" type="submit">
                Salvar
              </Button>
            ) : (
              <Button variant="danger" type="submit">
                Excluir
              </Button>
            )}
            <Button variant="secondary" type="reset">
              Cancelar
            </Button>
          </Col>
        </Row>
      </Form>
      <hr />
      <Table hover striped responsive items={users} fields={fields} />
    </div>
  )
}
