// frontend/src/components/article/ArticlesByCategory.vue
<template>
	<div class="articles-by-category">
		<PageTitle icon="fa fa-folder-o" :main="category.name" sub="Categoria" />
		<ul class="list-unstyled">
			<li v-for="article in articles" :key="article.id">
				<ArticleItem :article="article" />
			</li>
		</ul>
		<div class="load-more">
			<button
				v-if="loadMore"
				class="btn btn-lg btn-outline-primary"
				@click="getArticles"
			>
				Carregar Mais Artigos
			</button>
		</div>
	</div>
</template>

<script>
	import { baseApiUrl } from "@/global";
	import axios from "axios";
	import PageTitle from "../template/PageTitle.vue";
	import ArticleItem from "./ArticleItem.vue";

	export default {
		name: "ArticlesByCategory",
		components: { PageTitle, ArticleItem },
		data: function () {
			return {
				category: {},
				articles: [],
				page: 1,
				loadMore: true,
			};
		},
		methods: {
			getCategory() {
				const url = `${baseApiUrl}/categories/${this.category.id}`;
				axios(url).then((res) => (this.category = res.data));
			},
			getArticles() {
				const url = `${baseApiUrl}/categories/${this.category.id}/articles?page=${this.page}`;
				axios(url).then((res) => {
					this.articles = this.articles.concat(res.data);
					this.page++;

					if (res.data.length === 0) this.loadMore = false;
				});
			},
		},
		watch: {
			$route(to) {
				this.category.id = to.params.id;
				this.articles = [];
				this.page = 1;
				this.loadMore = true;

				this.getCategory();
				this.getArticles();
			},
		},
		mounted() {
			this.category.id = this.$route.params.id;
			this.getCategory();
			this.getArticles();
		},
	};
</script>

<style>
	.articles-by-category .load-more {
		display: flex;
		flex-direction: column;
		align-items: center;
		margin-top: 25px;
	}
</style>

// frontend-react/src/components/article/ArticlesByCategory.jsx
import React, { useEffect, useState } from 'react'
import { useParams } from 'react-router-dom'
import PageTitle from '../template/PageTitle'
import useLoadPartialData from '../../hooks/useLoadPartialData'
import useLoadData from '../../hooks/useLoadData'
import Button from 'react-bootstrap/Button'
import { showError } from '../../global'
import ArticleItem from './ArticleItem'

export default function ArticlesByCategory() {
  const { id: categoryId } = useParams()
  const [category] = useLoadData(`/categories/${categoryId}`, {
    name: '',
    id: '',
  })
  const [articles, loadMoreArticles] = useLoadPartialData(
    `/categories/${categoryId}/articles?page=`
  )
  const [loadMoreButton, setLoadMoreButton] = useState(true)

  function handleClickMoreArticles() {
    loadMoreArticles()
      .then((res) => {
        if (res?.data?.length === 0) setLoadMoreButton(false)
      })
      .catch(showError)
  }

  useEffect(() => {
    setLoadMoreButton(true)
  }, [categoryId])

  return (
    <div>
      <PageTitle
        icon="fa fa-folder-o"
        main={category.name || ''}
        sub="Categoria"
      />
      <ul className="list-unstyled">
        {articles.map((article) => {
          return <ArticleItem key={article.id} article={article} />
        })}
      </ul>
      <div className="d-flex flex-column align-items-center">
        {loadMoreButton && (
          <Button
            type="button"
            variant="outline-primary"
            size="lg"
            onClick={handleClickMoreArticles}>
            Carregar Mais Artigos
          </Button>
        )}
      </div>
    </div>
  )
}
