// frontend-react/src/components/template/Menu.jsx
import React, { useState, useDeferredValue } from 'react'
import styled from 'styled-components'
import { useSelector } from 'react-redux'
import Tree from '../utils/DataTree'
import useLoadData from '../../hooks/useLoadData'

const StyledAside = styled.aside`
  grid-area: menu;
  background: linear-gradient(to right, #232526, #414345);

  display: ${({ isMenuVisible }) => (isMenuVisible ? 'flex' : 'none')};
  flex-direction: column;
  flex-wrap: wrap;
  & .menu-filter {
    display: flex;
    justify-content: center;
    align-items: center;

    margin: 20px;
    padding-bottom: 8px;
    border-bottom: 1px solid #aaa;
  }

  & .menu-filter i {
    color: #aaa;
    margin-right: 10px;
  }

  & input {
    color: #ccc;
    font-size: 1.3rem;
    border: 0;
    outline: 0;
    width: 100%;
    background: transparent;
  }
`

export default function Menu() {
  const isMenuVisible = useSelector((state) => state.menu.isMenuVisible)
  const isUserSet = useSelector((state) => state.user.info)
  const [treeFilter, setTreeFilter] = useState('')
  const deferredTreeFilter = useDeferredValue(treeFilter)
  const [treeData] = useLoadData('/categories/tree')

  return (
    <StyledAside isMenuVisible={isMenuVisible && isUserSet}>
      <div className="menu-filter">
        <i className="fa fa-search fa-lg"></i>
        <input
          type="text"
          value={treeFilter}
          onChange={(e) => setTreeFilter(e.target.value)}
          className="filter-field"
          placeholder="Digite para filtrar..."
        />
      </div>
      <Tree data={treeData} filter={deferredTreeFilter} />
    </StyledAside>
  )
}

// frontend/src/components/template/Menu.vue
<template>
	<aside class="menu" v-show="isMenuVisible">
		<div class="menu-filter">
			<i class="fa fa-search fa-lg"></i>
			<input
				type="text"
				v-model="treeFilter"
				class="filter-field"
				placeholder="Digite para filtrar..."
			/>
		</div>
		<Tree
			:data="treeData"
			:options="treeOptions"
			ref="tree"
			:filter="treeFilter"
		/>
	</aside>
</template>

<script>
	import { mapState } from "vuex";
	import Tree from "liquor-tree";
	import { baseApiUrl } from "@/global";
	import axios from "axios";

	export default {
		name: "Menu",
		components: { Tree },
		computed: mapState(["isMenuVisible"]),
		data: function () {
			return {
				treeFilter: "",
				treeData: this.getTreeData(),
				treeOptions: {
					propertyNames: { text: "name" },
					filter: { emptyText: "Categoria não encontrada" },
				},
			};
		},
		methods: {
			getTreeData() {
				const url = `${baseApiUrl}/categories/tree`;
				return axios.get(url).then((res) => res.data);
			},
			onNodeSelect(node) {
				this.$router.push({
					name: "articlesByCategory",
					params: { id: node.id },
				});

				if (this.$mq === "xs" || this.$mq === "sm") {
					this.$store.commit("toggleMenu", false);
				}
			},
		},
		mounted() {
			this.$refs.tree.$on("node:selected", this.onNodeSelect);
		},
	};
</script>

<style>
	.menu {
		grid-area: menu;
		background: linear-gradient(to right, #232526, #414345);

		display: flex;
		flex-direction: column;
		flex-wrap: wrap;
	}

	.menu a,
	.menu a:hover {
		color: #fff;
		text-decoration: none;
	}

	.menu .tree-node.selected > .tree-content,
	.menu .tree-node .tree-content:hover {
		background-color: rgba(255, 255, 255, 0.2);
	}

	.tree-arrow.has-child {
		filter: brightness(2);
	}

	.menu .menu-filter {
		display: flex;
		justify-content: center;
		align-items: center;

		margin: 20px;
		padding-bottom: 8px;
		border-bottom: 1px solid #aaa;
	}

	.menu .menu-filter i {
		color: #aaa;
		margin-right: 10px;
	}

	.menu input {
		color: #ccc;
		font-size: 1.3rem;
		border: 0;
		outline: 0;
		width: 100%;
		background: transparent;
	}

	.tree-filter-empty {
		color: #ccc;
		font-size: 1.3rem;
		margin-left: 20px;
	}
</style>
