// frontend-react/src/components/template/PageTitle.jsx
import React from 'react'
import PropTypes from 'prop-types'
import styled from 'styled-components'

const Title = styled.h1`
  margin: 0px;
  font-size: 2.5rem;
`

const SubTitle = styled.h2`
  color: #777;
  margin-top: 5px;
  font-size: 1.3rem;
`

function PageTitle({ main, icon, sub }) {
  return (
    <div>
      <Title>
        {icon ? <i className={icon}></i> : null} {main}
      </Title>
      <SubTitle>{sub}</SubTitle>
      <hr />
    </div>
  )
}

PageTitle.propTypes = {
  main: PropTypes.string.isRequired,
  sub: PropTypes.string.isRequired,
  icon: PropTypes.string,
}

export default PageTitle

// frontend/src/components/template/PageTitle.vue
<template>
	<div class="page-title">
		<h1><i v-if="icon" :class="icon"></i> {{ main }}</h1>
		<h2>{{ sub }}</h2>
		<hr />
	</div>
</template>

<script>
	export default {
		name: "PageTitle",
		props: ["icon", "main", "sub"],
	};
</script>

<style>
	.page-title h1 {
		margin: 0px;
	}

	.page-title h2 {
		color: #777;
		margin-top: 5px;
		font-size: 1.3rem;
	}
</style>
