// frontend-react/src/components/admin/AdminPages.jsx
import React from 'react'
import PageTitle from '../template/PageTitle'
import ArticleAdmin from './ArticleAdmin'
import CategoryAdmin from './CategoryAdmin'
import UserAdmin from './UserAdmin'
import Nav from 'react-bootstrap/Nav'
import Tab from 'react-bootstrap/Tab'
import Card from 'react-bootstrap/Card'

export default function AdminPages() {
  return (
    <div>
      <PageTitle
        icon="fa fa-cogs"
        main="Administração do Sistema"
        sub="Cadastros & Cia"
      />
      <div>
        <Card>
          <Tab.Container defaultActiveKey={'articles'}>
            <Card.Header>
              <Nav variant="tabs">
                <Nav.Item>
                  <Nav.Link eventKey="articles" style={{ cursor: 'pointer' }}>
                    Artigos
                  </Nav.Link>
                </Nav.Item>
                <Nav.Item>
                  <Nav.Link eventKey="categories" style={{ cursor: 'pointer' }}>
                    Categorias
                  </Nav.Link>
                </Nav.Item>
                <Nav.Item>
                  <Nav.Link eventKey="users" style={{ cursor: 'pointer' }}>
                    Usuários
                  </Nav.Link>
                </Nav.Item>
              </Nav>
            </Card.Header>
            <Card.Body>
              <Tab.Content>
                <Tab.Pane eventKey={'articles'}>
                  <ArticleAdmin />
                </Tab.Pane>
                <Tab.Pane eventKey={'categories'}>
                  <CategoryAdmin />
                </Tab.Pane>
                <Tab.Pane eventKey={'users'}>
                  <UserAdmin />
                </Tab.Pane>
              </Tab.Content>
            </Card.Body>
          </Tab.Container>
        </Card>
      </div>
    </div>
  )
}

// frontend/src/components/admin/AdminPages.vue
<template>
	<div class="admin-pages">
		<PageTitle
			icon="fa fa-cogs"
			main="Administração do Sistema"
			sub="Cadastros & Cia"
		/>
		<div class="admin-pages-tabs">
			<b-card no-body>
				<b-tabs card>
					<b-tab title="Artigos" active>
						<ArticleAdmin />
					</b-tab>
					<b-tab title="Categorias">
						<CategoryAdmin />
					</b-tab>
					<b-tab title="Usuários">
						<UserAdmin />
					</b-tab>
				</b-tabs>
			</b-card>
		</div>
	</div>
</template>

<script>
	import PageTitle from "../template/PageTitle.vue";
	import ArticleAdmin from "./ArticleAdmin.vue";
	import CategoryAdmin from "./CategoryAdmin.vue";
	import UserAdmin from "./UserAdmin.vue";

	export default {
		name: "AdminPages",
		components: { PageTitle, ArticleAdmin, CategoryAdmin, UserAdmin },
	};
</script>

<style>
</style>
