// frontend-react/src/components/admin/ArticleAdmin.jsx
import React, { useState, useMemo } from 'react'
import axios from 'axios'
import { baseApiUrl, showError, showSuccess } from '../../global'
import FormGroupControl from '../utils/FormGroupControl'
import DataSelect from '../utils/DataSelect'
import Form from 'react-bootstrap/Form'
import DataPagination from '../utils/DataPagination'
import Button from 'react-bootstrap/Button'
import useObjectState from '../../hooks/useObjectState'
import useLoadData from '../../hooks/useLoadData'
import DataTable from '../utils/DataTable'
import QuillEditor from '../utils/QuillEditor'

export default function ArticleAdmin() {
  const [mode, setMode] = useState('save')
  const [page, setPage] = useState(1)
  const [validated, setValidated] = useState(false)
  const initialArticle = {
    id: undefined,
    name: '',
    categoryId: undefined,
    description: '',
    content: '',
    imageUrl: '',
    userId: undefined,
  }
  const [article, setArticle] = useObjectState(initialArticle)
  const [articles, loadArticles] = useLoadData(`/articles?page=${page}`, {
    data: [],
    count: 0,
    limit: 1,
  })
  const [categories] = useLoadData('/categories')
  const [users] = useLoadData('/users')
  const fields = useMemo(() => {
    const loadArticle = (article, mode = 'save') => {
      axios
        .get(`${baseApiUrl}/articles/${article.id}`)
        .then((res) => {
          setArticle(res.data)
          setMode(mode)
        })
        .catch(showError)
    }
    return [
      { key: 'id', label: 'Código', sortable: true },
      { key: 'name', label: 'Nome', sortable: true },
      { key: 'description', label: 'Descrição', sortable: true },
      {
        key: 'actions',
        label: 'Ações',
        formatter: (item) => {
          return (
            <div className="d-flex gap-2 flex-wrap">
              <Button variant="warning" onClick={() => loadArticle(item)}>
                <i className="fa fa-pencil"></i>
              </Button>
              <Button
                variant="danger"
                onClick={() => loadArticle(item, 'remove')}>
                <i className="fa fa-trash"></i>
              </Button>
            </div>
          )
        },
      },
    ]
    // eslint-disable-next-line
  }, [])

  const reset = () => {
    setMode('save')
    setArticle(initialArticle)
    setValidated(false)
  }

  const submit = () => {
    setValidated(true)
    const method = mode === 'remove' ? 'delete' : article.id ? 'put' : 'post'
    const id = article.id ? `/${article.id}` : ''
    axios[method](`${baseApiUrl}/articles${id}`, article)
      .then(() => {
        showSuccess()
        reset()
        loadArticles()
      })
      .catch(showError)
  }

  return (
    <div>
      <Form
        className="d-grid gap-3"
        onReset={(e) => {
          e.preventDefault()
          reset()
        }}
        noValidate
        validated={validated}
        onSubmit={(e) => {
          e.preventDefault()
          submit()
        }}>
        <input type="hidden" id="article-id" value={article.id || ''} />
        <FormGroupControl
          type="name"
          value={article.name}
          label="Nome:"
          controlId={'article-name'}
          placeholder="Digite o Nome do Artigo..."
          required
          readOnly={mode === 'remove'}
          onChange={(e) => setArticle({ name: e.target.value })}
        />
        <FormGroupControl
          type="text"
          value={article.description}
          label="Descrição:"
          controlId={'article-description'}
          placeholder="Descreva o Artigo..."
          required
          readOnly={mode === 'remove'}
          onChange={(e) => setArticle({ description: e.target.value })}
        />
        {mode === 'save' && (
          <>
            <FormGroupControl
              type="text"
              value={article.imageUrl || ''}
              label="Imagem (URL):"
              controlId={'article-imageUrl'}
              placeholder="Informe a URL da Imagem..."
              readOnly={mode === 'remove'}
              onChange={(e) => setArticle({ imageUrl: e.target.value })}
            />
            <Form.Group controlId="article-category-id">
              <Form.Label>Categoria:</Form.Label>
              <DataSelect
                value={article.categoryId}
                items={categories.map((category) => {
                  return {
                    value: category.id,
                    text: category.path,
                  }
                })}
                required
                onChange={(e) =>
                  setArticle({ categoryId: e.target.value || null })
                }
              />
            </Form.Group>
            <Form.Group controlId="article-user-id">
              <Form.Label>Autor:</Form.Label>
              <DataSelect
                value={article.userId}
                items={users.map((user) => {
                  return {
                    value: user.id,
                    text: `${user.name} - ${user.email}`,
                  }
                })}
                required
                onChange={(e) => setArticle({ userId: e.target.value || null })}
              />
            </Form.Group>
            <Form.Group controlId="article-content">
              <Form.Label>Conteúdo:</Form.Label>
              <QuillEditor
                value={article.content}
                onChange={(content) => setArticle({ content })}
                placeholder="Escreva o Artigo..."
                required
              />
            </Form.Group>
          </>
        )}
        <div className="d-flex gap-2">
          {mode === 'save' ? (
            <Button variant="primary" type="submit">
              Salvar
            </Button>
          ) : (
            <Button variant="danger" type="submit">
              Excluir
            </Button>
          )}
          <Button variant="secondary" type="reset">
            Cancelar
          </Button>
        </div>
      </Form>
      <hr />
      <DataTable
        hover
        striped
        responsive
        items={articles.data}
        fields={fields}
      />
      <DataPagination
        count={articles.count}
        page={page}
        limit={articles.limit}
        onChange={setPage}
      />
    </div>
  )
}

// frontend/src/components/admin/ArticleAdmin.vue
<template>
	<div class="article-admin">
		<b-form>
			<input type="hidden" id="article-id" v-model="article.id" />
			<b-form-group label="Nome:" label-for="article-name">
				<b-form-input
					id="article-name"
					type="text"
					v-model="article.name"
					required
					:readonly="mode === 'remove'"
					placeholder="Informe o Nome do Artigo..."
				></b-form-input>
			</b-form-group>
			<b-form-group label="Descrição:" label-for="article-description">
				<b-form-input
					id="article-description"
					type="text"
					v-model="article.description"
					required
					:readonly="mode === 'remove'"
					placeholder="Descreva..."
				></b-form-input>
			</b-form-group>
			<b-form-group
				v-if="mode === 'save'"
				label="Imagem (URL):"
				label-for="article-image-url"
			>
				<b-form-input
					id="article-image-url"
					type="text"
					v-model="article.imageUrl"
					required
					placeholder="Informe a URL da Imagem..."
				></b-form-input>
			</b-form-group>
			<b-form-group
				v-if="mode === 'save'"
				label="Categoria:"
				label-for="article-category-id"
			>
				<b-form-select
					id="article-category-id"
					:options="categories"
					v-model="article.categoryId"
				></b-form-select>
			</b-form-group>
			<b-form-group
				v-if="mode === 'save'"
				label="Autor:"
				label-for="article-user-id"
			>
				<b-form-select
					id="article-user-id"
					:options="users"
					v-model="article.userId"
				></b-form-select>
			</b-form-group>
			<b-form-group
				v-if="mode === 'save'"
				label="Conteúdo:"
				label-for="article-content"
			>
				<VueEditor v-model="article.content" placeholder="Informe o Conteúdo" />
			</b-form-group>
			<b-button variant="primary" v-if="mode === 'save'" @click="save"
				>Salvar</b-button
			>
			<b-button variant="danger" v-if="mode === 'remove'" @click="remove"
				>Excluir</b-button
			>
			<b-button class="ml-2" @click="reset">Cancelar</b-button>
		</b-form>
		<hr />
		<b-table hover striped :items="articles" :fields="fields">
			<template slot="actions" slot-scope="data">
				<b-button
					variant="warning"
					@click="loadArticle(data.item)"
					class="mr-2"
				>
					<i class="fa fa-pencil"></i>
				</b-button>
				<b-button variant="danger" @click="loadArticle(data.item, 'remove')">
					<i class="fa fa-trash"></i>
				</b-button>
			</template>
		</b-table>
		<b-pagination
			size="md"
			v-model="page"
			:total-rows="count"
			:per-page="limit"
		/>
	</div>
</template>

<script>
	import { VueEditor } from "vue2-editor";
	import { baseApiUrl, showError } from "@/global";
	import axios from "axios";

	export default {
		name: "ArticleAdmin",
		components: { VueEditor },
		data: function () {
			return {
				mode: "save",
				article: {},
				articles: [],
				categories: [],
				users: [],
				page: 1,
				limit: 0,
				count: 0,
				fields: [
					{ key: "id", label: "Código", sortable: true },
					{ key: "name", label: "Nome", sortable: true },
					{ key: "description", label: "Descrição", sortable: true },
					{ key: "actions", label: "Ações" },
				],
			};
		},
		methods: {
			loadArticles() {
				const url = `${baseApiUrl}/articles?page=${this.page}`;
				axios.get(url).then((res) => {
					this.articles = res.data.data;
					this.count = res.data.count;
					this.limit = res.data.limit;
				});
			},
			reset() {
				this.mode = "save";
				this.article = {};
				this.loadArticles();
			},
			save() {
				const method = this.article.id ? "put" : "post";
				const id = this.article.id ? `/${this.article.id}` : "";
				axios[method](`${baseApiUrl}/articles${id}`, this.article)
					.then(() => {
						this.$toasted.global.defaultSuccess();
						this.reset();
					})
					.catch(showError);
			},
			remove() {
				const id = this.article.id;
				axios
					.delete(`${baseApiUrl}/articles/${id}`)
					.then(() => {
						this.$toasted.global.defaultSuccess();
						this.reset();
					})
					.catch(showError);
			},
			loadArticle(article, mode = "save") {
				this.mode = mode;
				axios
					.get(`${baseApiUrl}/articles/${article.id}`)
					.then((res) => (this.article = res.data))
					.catch(showError);
			},
			loadCategories() {
				const url = `${baseApiUrl}/categories`;
				axios.get(url).then((res) => {
					this.categories = res.data.map((category) => {
						return { value: category.id, text: category.path };
					});
				});
			},
			loadUsers() {
				const url = `${baseApiUrl}/users`;
				axios.get(url).then((res) => {
					this.users = res.data.map((user) => {
						return { value: user.id, text: `${user.name} - ${user.email}` };
					});
				});
			},
		},
		watch: {
			page() {
				this.loadArticles(this.page);
			},
		},
		mounted() {
			this.loadUsers();
			this.loadCategories();
			this.loadArticles();
		},
	};
</script>

<style>
</style>
