// frontend-react/src/components/article/ArticleById.jsx
import React, { useEffect } from 'react'
import PageTitle from '../template/PageTitle'
import useLoadData from '../../hooks/useLoadData'
import { useParams } from 'react-router-dom'
import styled from 'styled-components'
import { sanitize } from 'dompurify'
import 'highlight.js/styles/dracula.css'
import hljs from 'highlight.js'

const StyledContent = styled.div`
  & {
    background-color: #fff;
    border-radius: 8px;
    padding: 25px;
  }

  & pre {
    padding: 20px;
    border-radius: 8px;
    font-size: 1.2rem;
    background-color: #1e1e1e;
    color: #fff;
  }

  & img {
    max-width: 100%;
  }

  & :last-child {
    margin-bottom: 0px;
  }
`

export default function ArticleById() {
  const { id: articleId } = useParams()
  const [article] = useLoadData(`/articles/${articleId}`, {
    name: '',
    description: '',
    content: '',
  })

  useEffect(() => {
    document.querySelectorAll('pre').forEach((el) => {
      hljs.highlightElement(el)
    })
  })
  return (
    <div className="article-by-id">
      <PageTitle
        icon="fa fa-file-o"
        main={article.name}
        sub={article.description}
      />
      <StyledContent
        dangerouslySetInnerHTML={{
          __html: sanitize(article.content),
        }}
      />
    </div>
  )
}

// frontend/src/components/article/ArticleById.vue
<template>
	<div class="article-by-id">
		<PageTitle
			icon="fa fa-file-o"
			:main="article.name"
			:sub="article.description"
		/>
		<div class="article-content" v-html="article.content"></div>
	</div>
</template>

<script>
	import "highlightjs/styles/dracula.css";
	import hljs from "highlightjs/highlight.pack.js";
	import { baseApiUrl } from "@/global";
	import axios from "axios";
	import PageTitle from "../template/PageTitle.vue";
	export default {
		name: "ArticleById",
		components: { PageTitle },
		data: function () {
			return {
				article: {},
			};
		},
		mounted() {
			const url = `${baseApiUrl}/articles/${this.$route.params.id}`;
			axios.get(url).then((res) => (this.article = res.data));
		},
		updated() {
			document.querySelectorAll(".article-content pre.ql-syntax").forEach((e) => {
				hljs.highlightBlock(e);
			});
		},
	};
</script>

<style>
	.article-content {
		background-color: #fff;
		border-radius: 8px;
		padding: 25px;
	}

	.article-content pre {
		padding: 20px;
		border-radius: 8px;
		font-size: 1.2rem;
		background-color: #1e1e1e;
		color: #fff;
	}

	.article-content img {
		max-width: 100%;
	}

	.article-content :last-child {
		margin-bottom: 0px;
	}
</style>
